export const MOVIEL_LIST_FETCH_SUCCESS = "MOVIEL_LIST_FETCH_SUCCESS";
export const MOVIEL_LIST_FETCH_FAILED = "MOVIEL_LIST_FETCH_FAILED";
export const MOVIE_DETAIL_FETCH_SUCCESS = "MOVIE_DETAIL_FETCH_SUCCESS";
export const MOVIE_DETAIL_FETCH_FAILED = "MOVIE_DETAIL_FETCH_FAILED";
export const MOVIEL_LOAD_MORE_SUCCESS = "MOVIEL_LOAD_MORE_SUCCESS";